language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://guppy0356.pactflow.io/
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "C+QzT7EiLCnmELeGekLFXgUhgv8kkCzbkq+R9C0amTEV5Cdafo0lmacWGykvZJnrMSDHeKswcYLADdMlQxTUPaOYqKY37NuZ5+k7AnR4byAUgYhOBsBPhc6iUeswqPNAylvBAy2VEpfhrIi+p200RWgltVclMpUDRjak7fVyAwYe1pi96125BXGDJg/sXJUR1QzKYKS7H2exf9N6OdkK2TguxMzsscbX+FrD/chWhwurWFnlhKaCm73nv20YSzpDFUM5+/vBW8qDqDgH7BWg/t7C/ywJE7B9pf2wZA18dkPBsM2YhspJP1vtKkyYznhrhGvFzp1WUyRbhrUfg2Av1cxSzcMb3QI3X0Dt21UgPdiFBXoN0HRxHnluB5gu9r/Ok3gsmV96klkHXxXUWer/1ZxDMlQ3TludD0Wr33z0pP6MW0IgGIXfVEp0fgOVvSt6TJUNST63dCDfPsG8hO3SNy/Fv3XQ49HG5nr0/ePS1LmzqWl4a1As10X/k6v3k7yF6a4p8j/roqtaYedp8WCAncHHVB0isW4wBXkWu8A6AZiESDReliyrsdtOqrLyIpNgkcwLh6TDh7WB2ejnZFTBkOJQqORv+CHP0P1cyuYPGnJDQGUiArIuVaVix0sfQsbdVcQo7Nyg6YxhQj53kbREk6b0KobBVCZ1bawq1iDzk44="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
